spring:
    datasource:
        hikari:
            jdbc-url: jdbc:mysql://localhost:3306/test
            username: root
            password: root
            driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: update
        show-sql: false
    security:
        jwt:
            secret-key: HQ58ZrkNESj8GM3k3FAM5jq1xIH32TgztewtBlHPca0=
            expiration: 86400000
            refresh-token:
                expiration: 86400000

logging:
    level:
        org:
            springframework:
                security: DEBUG
